project:
  type: website
  output-dir: docs
website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - You are welcome to use any template, but please do not use my posts."
    type: primary
    position: above-navbar
  title: "Home"
  repo-url: https://github.com/CreoHsia/myblog
  open-graph: true
  site-url: https://creohsia.github.io/myblog
  navbar:
    background: "#F8F2FF"
    border: true
    search: true
    left:
      - text: 'Blogs'
        href: blog.qmd
      - text: "Resources"
        href: resource/resource.qmd
    right: 
      - icon: twitter
        href: https://x.com/CreoHAHAHA
      - icon: github
        href: https://github.com/CreoHsia
      - icon: envelope
        href: mailto:creoxjz@gmail.com
  page-footer: 
    background: "#F8F2FF"
    left: "Made with ðŸ’œ and [Quarto](https://quarto.org/)" 
    right: 
      - icon: twitter
        href: https://x.com/CreoHAHAHA
      - icon: github
        href: https://github.com/CreoHsia
      - icon: envelope
        href: mailto:creoxjz@gmail.com

format:
  html:
    theme: 
      light: [cosmo,theme-light.scss]
      dark: [cosmo,theme-dark.scss]
    css: style.css
    highlight-style: ayu
    

editor: visual

